import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedGroup7153Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedLine97Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedLine98Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedMuhammadZakiAsyariWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedProfilKamuWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedLine99Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/Generated085Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedMhmdzakigmailcomWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedLine101Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedEditWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedGroup7156Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedLine100Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedJlTernateGg1No22RT05RW02Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedPengaturanakunWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget/generated/GeneratedGroup7154Widget1.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 322.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(255, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 42.00001525878906,
                              top: 272.002197265625,
                              right: null,
                              bottom: null,
                              width: 40.02490234375,
                              height: 315.0,
                              child: GeneratedGroup7153Widget(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 283.04931640625,
                              height: 103.5,
                              child: GeneratedGroup7156Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 26.0,
                              child: GeneratedProfilKamuWidget(),
                            ),
                            Positioned(
                              left: 168.0,
                              top: 762.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 44.0,
                              child: GeneratedGroup7154Widget1(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 485.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 44.0,
                              child: GeneratedJlTernateGg1No22RT05RW02Widget(),
                            ),
                            Positioned(
                              left: 98.77491760253906,
                              top: 598.00390625,
                              right: null,
                              bottom: null,
                              width: 352.00384521484375,
                              height: 1.0,
                              child: GeneratedLine97Widget(),
                            ),
                            Positioned(
                              left: 18.018402099609375,
                              top: 331.002197265625,
                              right: null,
                              bottom: null,
                              width: 280.0101013183594,
                              height: 1.0,
                              child: GeneratedLine98Widget(),
                            ),
                            Positioned(
                              left: 16.022079467773438,
                              top: 537.256591796875,
                              right: null,
                              bottom: null,
                              width: 282.00482177734375,
                              height: 1.0,
                              child: GeneratedLine99Widget(),
                            ),
                            Positioned(
                              left: 18.002593994140625,
                              top: 468.502197265625,
                              right: null,
                              bottom: null,
                              width: 280.0446472167969,
                              height: 1.0,
                              child: GeneratedLine100Widget(),
                            ),
                            Positioned(
                              left: 17.01690673828125,
                              top: 398.502197265625,
                              right: null,
                              bottom: null,
                              width: 281.0160217285156,
                              height: 1.0,
                              child: GeneratedLine101Widget(),
                            ),
                            Positioned(
                              left: 108.02491760253906,
                              top: 352.002197265625,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 31.0,
                              child: Generated085Widget(),
                            ),
                            Positioned(
                              left: 108.02207946777344,
                              top: 421.0,
                              right: null,
                              bottom: null,
                              width: 184.0,
                              height: 35.0,
                              child: GeneratedMhmdzakigmailcomWidget(),
                            ),
                            Positioned(
                              left: 107.0,
                              top: 279.0,
                              right: null,
                              bottom: null,
                              width: 192.0,
                              height: 27.0,
                              child: GeneratedMuhammadZakiAsyariWidget(),
                            ),
                            Positioned(
                              left: 248.0,
                              top: 209.0,
                              right: null,
                              bottom: null,
                              width: 55.0,
                              height: 25.0,
                              child: GeneratedEditWidget(),
                            ),
                            Positioned(
                              left: 108.02491760253906,
                              top: 554.002197265625,
                              right: null,
                              bottom: null,
                              width: 157.0,
                              height: 28.0,
                              child: GeneratedPengaturanakunWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
