import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7272Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7302Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7308Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7269Widget.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7270Widget.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7205Widget.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7271Widget.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7251Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedBelumadapesananWidget.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratediconbellWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedGroup7251Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedbelumbayarwidget3/generated/GeneratedRectangle55Widget1.dart';

/* Frame Belum Bayar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBelumBayarWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 342.0,
                              top: 332.0,
                              right: null,
                              bottom: null,
                              width: 1034.0,
                              height: 633.0,
                              child: GeneratedRectangle55Widget1(),
                            ),
                            Positioned(
                              left: 782.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 155.0,
                              height: 183.0,
                              child: GeneratedGroup7205Widget(),
                            ),
                            Positioned(
                              left: 779.0,
                              top: 724.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 26.0,
                              child: GeneratedBelumadapesananWidget(),
                            ),
                            Positioned(
                              left: 186.0,
                              top: 115.0,
                              right: null,
                              bottom: null,
                              width: 1208.0,
                              height: 113.828125,
                              child: GeneratedGroup7251Widget2(),
                            ),
                            Positioned(
                              left: 1071.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 42.6953125,
                              child: GeneratedGroup7251Widget3(),
                            ),
                            Positioned(
                              left: 31.0,
                              top: 307.0,
                              right: null,
                              bottom: null,
                              width: 282.5,
                              height: 618.029541015625,
                              child: GeneratedGroup7269Widget(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 569.0,
                              right: null,
                              bottom: null,
                              width: 185.0,
                              height: 124.97190856933594,
                              child: GeneratedGroup7270Widget(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 731.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 47.0,
                              child: GeneratedGroup7271Widget(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 649.0,
                              right: null,
                              bottom: null,
                              width: 218.0,
                              height: 58.171875,
                              child: GeneratedGroup7272Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.023241511980692544;

                                final double height =
                                    constraints.maxHeight * 0.03209201220808358;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.044444444444444446,
                                      y: constraints.maxHeight *
                                          0.6344827586206897,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconbellWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7302Widget1(),
                            ),
                            Positioned(
                              left: 457.0,
                              top: 253.0,
                              right: null,
                              bottom: null,
                              width: 902.0,
                              height: 54.0,
                              child: GeneratedGroup7308Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
