import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7251Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7209Widget4.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7253Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedBelumadaupdatepesananWidget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7304Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7291Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7253Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7295Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7261Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7260Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7294Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget3/generated/GeneratedGroup7306Widget1.dart';

/* Frame Notifikasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifikasiWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 361.0,
                              top: 335.0,
                              right: null,
                              bottom: null,
                              width: 1034.0,
                              height: 633.0,
                              child: GeneratedRectangle55Widget(),
                            ),
                            Positioned(
                              left: 800.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 155.0,
                              height: 183.0,
                              child: GeneratedGroup7209Widget4(),
                            ),
                            Positioned(
                              left: 748.0,
                              top: 733.0,
                              right: null,
                              bottom: null,
                              width: 259.0,
                              height: 26.0,
                              child: GeneratedBelumadaupdatepesananWidget(),
                            ),
                            Positioned(
                              left: 145.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 1208.0,
                              height: 113.4296875,
                              child: GeneratedGroup7253Widget(),
                            ),
                            Positioned(
                              left: 1062.0,
                              top: 33.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 41.765625,
                              child: GeneratedGroup7253Widget1(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 282.5,
                              height: 618.029541015625,
                              child: GeneratedGroup7251Widget1(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 282.5,
                              height: 618.029541015625,
                              child: GeneratedGroup7261Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.027777777777777776;

                                final double height =
                                    constraints.maxHeight * 0.0390625;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.043055555555555555,
                                      y: constraints.maxHeight * 0.630859375,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroup7260Widget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 636.0,
                              right: null,
                              bottom: null,
                              width: 218.0,
                              height: 47.0,
                              child: GeneratedGroup7291Widget(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 50.0,
                              child: GeneratedGroup7295Widget1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 711.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 59.0,
                              child: GeneratedGroup7294Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7304Widget(),
                            ),
                            Positioned(
                              left: 426.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 902.0,
                              height: 54.0,
                              child: GeneratedGroup7306Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
