import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7189Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/Generated25Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7114Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7105Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7193Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7106Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/Generated15Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7192Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7194Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRp655000Rp542000Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7163Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRp760000Rp646000Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7180Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRp998000Rp748000Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRp990000Rp792000Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRp800000Rp640000Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7184Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7140Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7104Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7176Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/Generated15Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/Generated20Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRp780000Rp663000Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7181Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/Generated20Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7183Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7190Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7186Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedSpesialPenawaranWidget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7187Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedRpWidget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/GeneratedGroup7139Widget.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget/generated/Generated20Widget.dart';

/* Frame Spesial Offers
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSpesialOffersWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7104Widget1(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7105Widget1(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 657.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7139Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 657.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7140Widget2(),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7106Widget1(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7114Widget1(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 40.0,
                              child: GeneratedSpesialPenawaranWidget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 26.0,
                              child: GeneratedRpWidget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 50.0,
                              child: GeneratedRp800000Rp640000Widget(),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: Generated20Widget(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 50.0,
                              child: GeneratedRp780000Rp663000Widget(),
                            ),
                            Positioned(
                              left: 359.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 29.0,
                              child: Generated15Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 586.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 50.0,
                              child: GeneratedRp998000Rp748000Widget(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 29.0,
                              child: Generated25Widget(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 836.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 50.0,
                              child: GeneratedRp990000Rp792000Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 113.0,
                              height: 50.0,
                              child: GeneratedRp655000Rp542000Widget(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 50.0,
                              child: GeneratedRp760000Rp646000Widget(),
                            ),
                            Positioned(
                              left: 356.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 29.0,
                              child: Generated15Widget1(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7180Widget(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7183Widget(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7186Widget(),
                            ),
                            Positioned(
                              left: 381.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7189Widget1(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7176Widget(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 334.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7192Widget(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7193Widget(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7194Widget1(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7181Widget(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7184Widget(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7187Widget(),
                            ),
                            Positioned(
                              left: 381.0,
                              top: 863.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7190Widget(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 66.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7163Widget(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 662.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: Generated20Widget1(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 662.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: Generated20Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
