import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7192Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/Generated20Widget4.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7189Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7140Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7104Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRp990000Rp792000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRp655000Rp542000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7186Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7180Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRpWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/Generated15Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7187Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRp780000Rp663000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7176Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7194Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedSpesialPenawaranWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7184Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRp998000Rp748000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/Generated15Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7181Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/Generated20Widget5.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7163Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7114Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7139Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRp760000Rp646000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7105Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedRp800000Rp640000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7106Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7193Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7183Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/GeneratedGroup7190Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/Generated25Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedspesialofferswidget1/generated/Generated20Widget3.dart';

/* Frame Spesial Offers
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSpesialOffersWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7104Widget3(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7105Widget3(),
                            ),
                            Positioned(
                              left: 231.0,
                              top: 657.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7139Widget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 657.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7140Widget3(),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7106Widget3(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7114Widget3(),
                            ),
                            Positioned(
                              left: 112.0,
                              top: 71.0,
                              right: null,
                              bottom: null,
                              width: 244.0,
                              height: 40.0,
                              child: GeneratedSpesialPenawaranWidget3(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 26.0,
                              child: GeneratedRpWidget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 50.0,
                              child: GeneratedRp800000Rp640000Widget1(),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: Generated20Widget3(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 50.0,
                              child: GeneratedRp780000Rp663000Widget1(),
                            ),
                            Positioned(
                              left: 359.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 29.0,
                              child: Generated15Widget2(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 586.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 50.0,
                              child: GeneratedRp998000Rp748000Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 49.0,
                              height: 29.0,
                              child: Generated25Widget1(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 836.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 50.0,
                              child: GeneratedRp990000Rp792000Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 113.0,
                              height: 50.0,
                              child: GeneratedRp655000Rp542000Widget1(),
                            ),
                            Positioned(
                              left: 241.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 50.0,
                              child: GeneratedRp760000Rp646000Widget1(),
                            ),
                            Positioned(
                              left: 356.0,
                              top: 156.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 29.0,
                              child: Generated15Widget3(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7180Widget1(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7183Widget1(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7186Widget1(),
                            ),
                            Positioned(
                              left: 381.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7189Widget3(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7176Widget1(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 334.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7192Widget1(),
                            ),
                            Positioned(
                              left: 372.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7193Widget1(),
                            ),
                            Positioned(
                              left: 176.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7194Widget3(),
                            ),
                            Positioned(
                              left: 380.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7181Widget1(),
                            ),
                            Positioned(
                              left: 185.0,
                              top: 613.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7184Widget1(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 868.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7187Widget1(),
                            ),
                            Positioned(
                              left: 381.0,
                              top: 863.0,
                              right: null,
                              bottom: null,
                              width: 16.0,
                              height: 16.0,
                              child: GeneratedGroup7190Widget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 66.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7163Widget1(),
                            ),
                            Positioned(
                              left: 154.0,
                              top: 662.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: Generated20Widget4(),
                            ),
                            Positioned(
                              left: 347.0,
                              top: 662.0,
                              right: null,
                              bottom: null,
                              width: 50.0,
                              height: 29.0,
                              child: Generated20Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
