import 'package:flutter/material.dart';

/* UndefinedNode Akun
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAkunWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
