import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget/generated/GeneratedRectangle2677Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget/generated/GeneratedGroup7237Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget/generated/GeneratedGroup7147Widget.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget/generated/GeneratedNotifikasiWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednotifikasiwidget/generated/GeneratedBelumadapesannotifikasiWidget.dart';

/* Frame Notifikasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotifikasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 958.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 91.0,
                              top: 53.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 29.0,
                              child: GeneratedNotifikasiWidget1(),
                            ),
                            Positioned(
                              left: 153.0,
                              top: 303.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 152.0,
                              child: GeneratedRectangle2677Widget(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 50.0,
                              child: GeneratedBelumadapesannotifikasiWidget(),
                            ),
                            Positioned(
                              left: 24.0,
                              top: 41.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7147Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 93.0,
                              child: GeneratedGroup7237Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
