import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedcode2widget9/generated/GeneratedRectangle18Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedcode2widget9/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatedcode2widget9/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedcode2widget9/generated/GeneratedRectangle17Widget3.dart';

/* Instance Code 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCode2Widget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 845.0,
      height: 126.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09467455621301775;

                final double height =
                    constraints.maxHeight * 0.6349206349206349;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: constraints.maxHeight * 0.36507936507936506,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle15Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09467455621301775;

                final double height =
                    constraints.maxHeight * 0.6349206349206349;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.9053254437869822,
                      y: constraints.maxHeight * 0.36507936507936506,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle16Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09467455621301775;

                final double height =
                    constraints.maxHeight * 0.6349206349206349;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.6035502958579881,
                      y: constraints.maxHeight * 0.36507936507936506,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle17Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.09467455621301775;

                final double height =
                    constraints.maxHeight * 0.6349206349206349;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.30177514792899407,
                      y: constraints.maxHeight * 0.36507936507936506,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle18Widget3(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
