import 'package:flutter/material.dart';

/* UndefinedNode Telepon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTeleponWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
