import 'package:flutter/material.dart';

/* UndefinedNode Ovo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOvoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
