import 'package:flutter/material.dart';

/* UndefinedNode Harga
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHargaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
