import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedlogin3widget4/generated/GeneratedMhmd_Zaki16gmailcomWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatedlogin3widget4/generated/GeneratedWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedlogin3widget4/generated/GeneratedLogin2Widget4.dart';

/* Instance Login 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin3Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 596.0,
      height: 307.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedLogin2Widget4(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5855704697986577;

                final double height =
                    constraints.maxHeight * 0.1270358306188925;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0436241610738255,
                      y: constraints.maxHeight * 0.23127035830618892,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMhmd_Zaki16gmailcomWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.6308724832214765;

                final double height =
                    constraints.maxHeight * 0.25732899022801303;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.0436241610738255,
                      y: constraints.maxHeight * 0.6547231270358306,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedWidget1(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
