import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedRectangle2607Widget4.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedReebokZpump25Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedConverseWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNikeHyperAdaptWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedPumaWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNikeWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedRectangle2605Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNikeAirJordanWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNikeWidget4.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNewBaWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAsics2Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedPumaWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7201Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedEllipse25Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedConverse1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedSpesialPenawaranWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAdidasWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAdidas1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAsicsWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedSemuaWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7235Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7232Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedLainnyaWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedRectangle2604Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7200Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedReebok1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNikeAirMaxFlyknitWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedRectangle2606Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedReebokWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7236Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAllWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAdidasWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedNb1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedRectangle2603Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7234Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedPopulerWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedPuma1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedAsicsWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedGroup7232Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedEllipse23Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedEllipse26Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget/generated/GeneratedEllipse24Widget.dart';

/* Frame Home Pages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePagesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1462.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 428.0,
                            height: 1436.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(40.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(40.0),
                                    child: Container(
                                      color: Color.fromARGB(204, 17, 17, 17),
                                    ),
                                  ),
                                  Positioned(
                                    left: 22.0,
                                    top: 39.0,
                                    right: null,
                                    bottom: null,
                                    width: 384.0,
                                    height: 55.0,
                                    child: GeneratedInputWidget(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 142.0,
                                    right: null,
                                    bottom: null,
                                    width: 203.0,
                                    height: 26.0,
                                    child: GeneratedSpesialPenawaranWidget1(),
                                  ),
                                  Positioned(
                                    left: 31.0,
                                    top: 502.0,
                                    right: null,
                                    bottom: null,
                                    width: 150.00006103515625,
                                    height: 136.49986267089844,
                                    child: GeneratedEllipse23Widget(),
                                  ),
                                  Positioned(
                                    left: 135.0,
                                    top: 601.0,
                                    right: null,
                                    bottom: null,
                                    width: 42.0,
                                    height: 25.0,
                                    child: GeneratedNb1Widget(),
                                  ),
                                  Positioned(
                                    left: 230.0,
                                    top: 503.0,
                                    right: null,
                                    bottom: null,
                                    width: 152.09605407714844,
                                    height: 135.5,
                                    child: GeneratedEllipse24Widget(),
                                  ),
                                  Positioned(
                                    left: 239.0,
                                    top: 597.0,
                                    right: null,
                                    bottom: null,
                                    width: 34.0,
                                    height: 34.0,
                                    child: GeneratedConverse1Widget(),
                                  ),
                                  Positioned(
                                    left: 139.0,
                                    top: 510.0,
                                    right: null,
                                    bottom: null,
                                    width: 32.0,
                                    height: 28.0,
                                    child: GeneratedAdidas1Widget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 595.0,
                                    right: null,
                                    bottom: null,
                                    width: 44.0,
                                    height: 38.0,
                                    child: GeneratedReebok1Widget(),
                                  ),
                                  Positioned(
                                    left: 336.0,
                                    top: 639.0,
                                    right: null,
                                    bottom: null,
                                    width: 53.0,
                                    height: 24.0,
                                    child: GeneratedLainnyaWidget(),
                                  ),
                                  Positioned(
                                    left: 238.0,
                                    top: 508.0,
                                    right: null,
                                    bottom: null,
                                    width: 32.0,
                                    height: 35.0,
                                    child: GeneratedPuma1Widget(),
                                  ),
                                  Positioned(
                                    left: 239.0,
                                    top: 550.0,
                                    right: null,
                                    bottom: null,
                                    width: 56.0,
                                    height: 24.0,
                                    child: GeneratedPumaWidget(),
                                  ),
                                  Positioned(
                                    left: 333.0,
                                    top: 503.67510986328125,
                                    right: null,
                                    bottom: null,
                                    width: 49.0,
                                    height: 49.0,
                                    child: GeneratedEllipse25Widget(),
                                  ),
                                  Positioned(
                                    left: 339.0,
                                    top: 510.0,
                                    right: null,
                                    bottom: null,
                                    width: 34.0,
                                    height: 31.0,
                                    child: GeneratedAsics2Widget(),
                                  ),
                                  Positioned(
                                    left: 342.0,
                                    top: 551.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 21.0,
                                    child: GeneratedAsicsWidget(),
                                  ),
                                  Positioned(
                                    left: 131.0,
                                    top: 639.0,
                                    right: null,
                                    bottom: null,
                                    width: 62.0,
                                    height: 19.0,
                                    child: GeneratedNewBaWidget(),
                                  ),
                                  Positioned(
                                    left: 345.0,
                                    top: 601.0,
                                    right: null,
                                    bottom: null,
                                    width: 25.0,
                                    height: 25.0,
                                    child: GeneratedEllipse26Widget(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 637.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 27.0,
                                    child: GeneratedReebokWidget(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 515.0,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 24.799999237060547,
                                    child: GeneratedGroup7200Widget(),
                                  ),
                                  Positioned(
                                    left: 226.0,
                                    top: 640.0,
                                    right: null,
                                    bottom: null,
                                    width: 83.0,
                                    height: 30.0,
                                    child: GeneratedConverseWidget(),
                                  ),
                                  Positioned(
                                    left: 135.0,
                                    top: 550.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 24.0,
                                    child: GeneratedAdidasWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 550.0,
                                    right: null,
                                    bottom: null,
                                    width: 37.0,
                                    height: 24.0,
                                    child: GeneratedNikeWidget3(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 173.0,
                                    right: null,
                                    bottom: null,
                                    width: 283.0,
                                    height: 306.0,
                                    child: GeneratedImage1Widget(),
                                  ),
                                  Positioned(
                                    left: 351.0,
                                    top: 612.0,
                                    right: null,
                                    bottom: null,
                                    width: 14.0,
                                    height: 2.0,
                                    child: GeneratedGroup7201Widget(),
                                  ),
                                  Positioned(
                                    left: 22.0,
                                    top: 685.0,
                                    right: null,
                                    bottom: null,
                                    width: 81.0,
                                    height: 28.0,
                                    child: GeneratedPopulerWidget(),
                                  ),
                                  Positioned(
                                    left: 332.0,
                                    top: 686.0,
                                    right: null,
                                    bottom: null,
                                    width: 80.0,
                                    height: 27.0,
                                    child: GeneratedSemuaWidget(),
                                  ),
                                  Positioned(
                                    left: 18.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2603Widget(),
                                  ),
                                  Positioned(
                                    left: 172.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2604Widget(),
                                  ),
                                  Positioned(
                                    left: 256.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2606Widget(),
                                  ),
                                  Positioned(
                                    left: 340.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2607Widget4(),
                                  ),
                                  Positioned(
                                    left: 88.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2605Widget(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 23.0,
                                    child: GeneratedAllWidget(),
                                  ),
                                  Positioned(
                                    left: 103.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 41.0,
                                    height: 24.0,
                                    child: GeneratedNikeWidget4(),
                                  ),
                                  Positioned(
                                    left: 184.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 50.0,
                                    height: 23.0,
                                    child: GeneratedPumaWidget1(),
                                  ),
                                  Positioned(
                                    left: 267.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 48.0,
                                    height: 23.0,
                                    child: GeneratedAsicsWidget1(),
                                  ),
                                  Positioned(
                                    left: 349.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 60.0,
                                    height: 26.0,
                                    child: GeneratedAdidasWidget1(),
                                  ),
                                  Positioned(
                                    left: 224.0,
                                    top: 814.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7232Widget(),
                                  ),
                                  Positioned(
                                    left: 224.0,
                                    top: 1081.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7234Widget(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 1081.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7235Widget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 1277.0,
                                    right: null,
                                    bottom: null,
                                    width: 158.0,
                                    height: 42.0,
                                    child: GeneratedNikeAirJordanWidget1(),
                                  ),
                                  Positioned(
                                    left: 242.0,
                                    top: 1000.0,
                                    right: null,
                                    bottom: null,
                                    width: 141.0,
                                    height: 66.0,
                                    child: GeneratedReebokZpump25Widget(),
                                  ),
                                  Positioned(
                                    left: 242.0,
                                    top: 1267.0,
                                    right: null,
                                    bottom: null,
                                    width: 141.0,
                                    height: 66.0,
                                    child: GeneratedNikeAirMaxFlyknitWidget1(),
                                  ),
                                  Positioned(
                                    left: 40.0,
                                    top: 814.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7232Widget1(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 998.0,
                                    right: null,
                                    bottom: null,
                                    width: 179.0,
                                    height: 49.0,
                                    child: GeneratedNikeHyperAdaptWidget2(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: -26.0,
              width: 428.0,
              height: 93.0,
              child: GeneratedGroup7236Widget(),
            )
          ]),
    ));
  }
}
