import 'package:flutter/material.dart';

/* UndefinedNode Size 42
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSize42Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
