import 'package:flutter/material.dart';

/* UndefinedNode Bank Web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBankWebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
