import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7275Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7214Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7306Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7278Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7284Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedNikeKyrie6Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7281Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7280Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7286Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7141Widget5.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7279Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7283Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7247Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedLine42Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7285Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7282Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7276Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget/generated/GeneratedGroup7298Widget1.dart';

/* Frame Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProdukWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1537.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1537.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 305.0,
                              top: 1288.0,
                              right: null,
                              bottom: null,
                              width: 1003.0,
                              height: 1.0,
                              child: GeneratedLine42Widget(),
                            ),
                            Positioned(
                              left: 882.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7141Widget5(),
                            ),
                            Positioned(
                              left: 1064.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 42.16803741455078,
                              child: GeneratedGroup7214Widget3(),
                            ),
                            Positioned(
                              left: 147.0,
                              top: 125.0,
                              right: null,
                              bottom: null,
                              width: 1197.287841796875,
                              height: 102.50366973876953,
                              child: GeneratedGroup7247Widget(),
                            ),
                            Positioned(
                              left: 632.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 290.0,
                              child: GeneratedGroup7276Widget(),
                            ),
                            Positioned(
                              left: 898.0,
                              top: 541.0,
                              right: null,
                              bottom: null,
                              width: 160.0,
                              height: 36.0,
                              child: GeneratedNikeKyrie6Widget(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 647.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 317.0,
                              child: GeneratedGroup7279Widget(),
                            ),
                            Positioned(
                              left: 882.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 321.0,
                              child: GeneratedGroup7281Widget(),
                            ),
                            Positioned(
                              left: 1132.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 287.0,
                              child: GeneratedGroup7282Widget(),
                            ),
                            Positioned(
                              left: 1128.0,
                              top: 1009.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 313.0,
                              child: GeneratedGroup7286Widget(),
                            ),
                            Positioned(
                              left: 628.0,
                              top: 1009.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 279.0,
                              child: GeneratedGroup7284Widget(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 320.0,
                              child: GeneratedGroup7275Widget(),
                            ),
                            Positioned(
                              left: 1132.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 324.0,
                              child: GeneratedGroup7278Widget(),
                            ),
                            Positioned(
                              left: 878.0,
                              top: 1009.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 279.0,
                              child: GeneratedGroup7285Widget(),
                            ),
                            Positioned(
                              left: 378.0,
                              top: 1013.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 309.0,
                              child: GeneratedGroup7283Widget(),
                            ),
                            Positioned(
                              left: 632.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 321.0,
                              child: GeneratedGroup7280Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1402.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7298Widget1(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 222.0,
                              height: 571.0,
                              child: GeneratedGroup7306Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
