import 'package:flutter/material.dart';

/* UndefinedNode Gopay
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGopayWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
