import 'package:flutter/material.dart';

/* UndefinedNode Link aja
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLinkajaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
