import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedhalamanlogindaftarwidget/generated/GeneratedKELUARWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhalamanlogindaftarwidget/generated/GeneratedGroup7156Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhalamanlogindaftarwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhalamanlogindaftarwidget/generated/GeneratedDAFTARWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhalamanlogindaftarwidget/generated/GeneratedLine59Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhalamanlogindaftarwidget/generated/GeneratedSilahkanDaftaratauLoginterlebihdahulusupayabisamenikmat.dart';

/* Frame Halaman Login/daftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHalamanLogindaftarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 155.0,
                              child: GeneratedGroup7156Widget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 106.0,
                              right: null,
                              bottom: null,
                              width: 378.0,
                              height: 114.0,
                              child:
                                  GeneratedSilahkanDaftaratauLoginterlebihdahulusupayabisamenikmat(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 476.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 38.0,
                              child: GeneratedLOGINWidget(),
                            ),
                            Positioned(
                              left: 174.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 38.0,
                              child: GeneratedDAFTARWidget2(),
                            ),
                            Positioned(
                              left: 184.0,
                              top: 637.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 32.0,
                              child: GeneratedKELUARWidget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 379.0118713378906,
                              height: 3.0,
                              child: GeneratedLine59Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
