import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedKonfirmasiWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedLine133Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedRectangle2677Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedRectangle11Widget11.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedRectangle10Widget7.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedMasukWidget7.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedSportShoesWidget10.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedGroup9Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedloginwidget10/generated/GeneratedGroup7Widget1.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 1024.0,
                              child: GeneratedRectangle2677Widget2(),
                            ),
                            Positioned(
                              left: 589.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 276.0,
                              height: 56.0,
                              child: GeneratedSportShoesWidget10(),
                            ),
                            Positioned(
                              left: 302.0,
                              top: 219.0,
                              right: null,
                              bottom: null,
                              width: 901.0,
                              height: 685.0,
                              child: GeneratedRectangle10Widget7(),
                            ),
                            Positioned(
                              left: 373.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 145.0,
                              height: 59.0,
                              child: GeneratedMasukWidget7(),
                            ),
                            Positioned(
                              left: 646.0,
                              top: 797.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 74.0,
                              child: GeneratedGroup7Widget1(),
                            ),
                            Positioned(
                              left: 460.0,
                              top: 385.0,
                              right: null,
                              bottom: null,
                              width: 595.0,
                              height: 120.0,
                              child: GeneratedGroup8Widget1(),
                            ),
                            Positioned(
                              left: 460.0,
                              top: 562.0,
                              right: null,
                              bottom: null,
                              width: 595.0,
                              height: 120.0,
                              child: GeneratedGroup9Widget3(),
                            ),
                            Positioned(
                              left: 607.0,
                              top: 792.0,
                              right: null,
                              bottom: null,
                              width: 301.0,
                              height: 68.0,
                              child: GeneratedRectangle11Widget11(),
                            ),
                            Positioned(
                              left: 696.0,
                              top: 811.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 35.0,
                              child: GeneratedKonfirmasiWidget2(),
                            ),
                            Positioned(
                              left: 349.0,
                              top: 353.0,
                              right: null,
                              bottom: null,
                              width: 818.00244140625,
                              height: 1.0,
                              child: GeneratedLine133Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
