import 'package:flutter/material.dart';

/* UndefinedNode Indomaret Web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIndomaretWebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
