import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedLine134Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7297Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedStatistik1Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7308Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7295Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedTerjualWidget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7300Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7301Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7314Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7299Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedKategoriWidget1.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7296Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7316Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7309Widget.dart';
import 'package:flutterapp/shoessportapp/generateddasboardwidget/generated/GeneratedGroup7298Widget.dart';

/* Frame Dasboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDasboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 105.0,
                              child: GeneratedGroup7316Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7297Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 105.0,
                              right: null,
                              bottom: null,
                              width: 340.0,
                              height: 920.0,
                              child: GeneratedGroup7314Widget(),
                            ),
                            Positioned(
                              left: 401.0,
                              top: 191.0,
                              right: null,
                              bottom: null,
                              width: 558.0,
                              height: 259.0,
                              child: GeneratedGroup7308Widget(),
                            ),
                            Positioned(
                              left: 401.0,
                              top: 130.0,
                              right: null,
                              bottom: null,
                              width: 106.0,
                              height: 41.0,
                              child: GeneratedTerjualWidget(),
                            ),
                            Positioned(
                              left: 365.0,
                              top: 515.0,
                              right: null,
                              bottom: null,
                              width: 1052.0118408203125,
                              height: 5.0,
                              child: GeneratedLine134Widget(),
                            ),
                            Positioned(
                              left: 914.0,
                              top: 565.0,
                              right: null,
                              bottom: null,
                              width: 427.0,
                              height: 447.0,
                              child: GeneratedStatistik1Widget(),
                            ),
                            Positioned(
                              left: 399.0,
                              top: 632.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 96.0,
                              child: GeneratedGroup7296Widget(),
                            ),
                            Positioned(
                              left: 401.0,
                              top: 770.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 92.0,
                              child: GeneratedGroup7298Widget(),
                            ),
                            Positioned(
                              left: 567.0,
                              top: 770.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 92.0,
                              child: GeneratedGroup7299Widget(),
                            ),
                            Positioned(
                              left: 728.0,
                              top: 765.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 97.0,
                              child: GeneratedGroup7300Widget(),
                            ),
                            Positioned(
                              left: 398.0,
                              top: 894.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 99.0,
                              child: GeneratedGroup7309Widget(),
                            ),
                            Positioned(
                              left: 563.0,
                              top: 632.0,
                              right: null,
                              bottom: null,
                              width: 89.0,
                              height: 96.0,
                              child: GeneratedGroup7295Widget(),
                            ),
                            Positioned(
                              left: 728.0,
                              top: 632.0,
                              right: null,
                              bottom: null,
                              width: 88.0,
                              height: 97.0,
                              child: GeneratedGroup7301Widget(),
                            ),
                            Positioned(
                              left: 399.0,
                              top: 559.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 36.0,
                              child: GeneratedKategoriWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
