import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget2/generated/GeneratedGroup7212Widget3.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget2/generated/GeneratedSelamatpesananandasudahberhasilWidget.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget2/generated/GeneratedPesananandaakansegaradikirimWidget.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget2/generated/GeneratedGroup7211Widget3.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget2/generated/GeneratedGroup7210Widget1.dart';

/* Frame Done
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoneWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 124.0,
                              top: 88.0,
                              right: null,
                              bottom: null,
                              width: 1194.0,
                              height: 848.0,
                              child: GeneratedGroup7212Widget3(),
                            ),
                            Positioned(
                              left: 402.0,
                              top: 152.0,
                              right: null,
                              bottom: null,
                              width: 638.0,
                              height: 44.0,
                              child:
                                  GeneratedSelamatpesananandasudahberhasilWidget(),
                            ),
                            Positioned(
                              left: 556.0,
                              top: 302.0,
                              right: null,
                              bottom: null,
                              width: 327.0,
                              height: 327.0,
                              child: GeneratedGroup7210Widget1(),
                            ),
                            Positioned(
                              left: 562.0,
                              top: 684.0,
                              right: null,
                              bottom: null,
                              width: 324.0,
                              height: 86.0,
                              child:
                                  GeneratedPesananandaakansegaradikirimWidget(),
                            ),
                            Positioned(
                              left: 644.0,
                              top: 848.0,
                              right: null,
                              bottom: null,
                              width: 159.0,
                              height: 67.0,
                              child: GeneratedGroup7211Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
