import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedPembayaranWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedJlTernateGG1No23RT05RW02KelKasinKecKlojen65177NoHp085Wi.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedGroup7137Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedGroup7134Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedCheckoutWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratediconpinWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedLine82Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedCheckoutWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedGroup7132Widget5.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedGroup7146Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedPembayaranBankWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedGroup7142Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpemesanan2widget/generated/GeneratedNikeZoomKD10OreoSize42Rp789999Widget3.dart';

/* Frame Pemesanan2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPemesanan2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 117.0,
                              child: GeneratedGroup7137Widget1(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 150.0,
                              right: null,
                              bottom: null,
                              width: 354.0,
                              height: 741.0,
                              child: GeneratedGroup7134Widget2(),
                            ),
                            Positioned(
                              left: 19.0,
                              top: 247.0,
                              right: null,
                              bottom: null,
                              width: 388.0115966796875,
                              height: 1.0,
                              child: GeneratedLine82Widget1(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 444.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 38.0,
                              child: GeneratedGroup7142Widget1(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 61.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7132Widget5(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 68.0,
                              right: null,
                              bottom: null,
                              width: 121.0,
                              height: 37.0,
                              child: GeneratedCheckoutWidget(),
                            ),
                            Positioned(
                              left: 110.0,
                              top: 148.0,
                              right: null,
                              bottom: null,
                              width: 233.0,
                              height: 56.0,
                              child:
                                  GeneratedJlTernateGG1No23RT05RW02KelKasinKecKlojen65177NoHp085Wi(),
                            ),
                            Positioned(
                              left: 61.0,
                              top: 453.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 25.0,
                              child: GeneratedPembayaranWidget1(),
                            ),
                            Positioned(
                              left: 254.0,
                              top: 850.0,
                              right: null,
                              bottom: null,
                              width: 122.0,
                              height: 35.0,
                              child: GeneratedCheckoutWidget1(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 508.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 264.0,
                              child: GeneratedGroup7146Widget1(),
                            ),
                            Positioned(
                              left: 157.0,
                              top: 734.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 33.0,
                              child: GeneratedPembayaranBankWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.09813084112149532;

                                final double height =
                                    constraints.maxHeight * 0.04643628509719223;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.10046728971962617,
                                      y: constraints.maxHeight *
                                          0.1652267818574514,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratediconpinWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 155.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 240.0,
                              height: 80.0,
                              child:
                                  GeneratedNikeZoomKD10OreoSize42Rp789999Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
