import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget/generated/GeneratedGroup7189Widget.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget/generated/GeneratedGroup7188Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget/generated/GeneratedLine130Widget.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget/generated/GeneratedGroup7162Widget.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget/generated/GeneratedPesananSayaWidget1.dart';

/* Frame Pesanan Saya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananSayaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1112.5,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 26.0,
                              child: GeneratedPesananSayaWidget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 99.0,
                              right: null,
                              bottom: null,
                              width: 397.0,
                              height: 1.0,
                              child: GeneratedLine130Widget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 146.0,
                              child: GeneratedGroup7189Widget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 31.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7188Widget1(),
                            ),
                            Positioned(
                              left: -1421.0,
                              top: 612.5,
                              right: null,
                              bottom: null,
                              width: 2009.0,
                              height: 500.0,
                              child: GeneratedGroup7162Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.0848345890223423;

                                final double height =
                                    constraints.maxHeight * 0.03644827478132804;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.3294392523364486,
                                      y: constraints.maxHeight *
                                          0.9449244060475162,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedGroupWidget4(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
