import 'package:flutter/material.dart';

/* UndefinedNode Ovo Web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOvoWebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
