import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedConverseWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedRectangle2605Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedNb1Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedEllipse25Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedReebokZpump25Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedEllipse23Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7234Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedRectangle2603Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedRectangle2607Widget9.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedPumaWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAdidasWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7201Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedNikeHyperAdaptWidget5.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAllWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7238Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedSpesialPenawaranWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7232Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedReebokWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAsicsWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7200Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7235Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAdidas1Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedEllipse24Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedNewBalWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAsicsWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedConverse1Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedGroup7237Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedNikeWidget9.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedNikeAirMaxFlyknitWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedRectangle2604Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAdidasWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedSemuaWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedPuma1Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedRectangle2606Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedAsics2Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedPumaWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedNikeAirJordanWidget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedReebok1Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedPopulerWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedEllipse26Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget1/generated/GeneratedMoreWidget.dart';

/* Frame Home Pages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePagesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1466.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 428.0,
                            height: 1436.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(40.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(40.0),
                                    child: Container(
                                      color: Color.fromARGB(204, 17, 17, 17),
                                    ),
                                  ),
                                  Positioned(
                                    left: 22.0,
                                    top: 45.0,
                                    right: null,
                                    bottom: null,
                                    width: 384.0,
                                    height: 55.0,
                                    child: GeneratedInputWidget2(),
                                  ),
                                  Positioned(
                                    left: 29.0,
                                    top: 142.0,
                                    right: null,
                                    bottom: null,
                                    width: 224.0,
                                    height: 26.0,
                                    child: GeneratedSpesialPenawaranWidget2(),
                                  ),
                                  Positioned(
                                    left: 31.0,
                                    top: 502.0,
                                    right: null,
                                    bottom: null,
                                    width: 150.00006103515625,
                                    height: 136.49986267089844,
                                    child: GeneratedEllipse23Widget1(),
                                  ),
                                  Positioned(
                                    left: 135.0,
                                    top: 601.0,
                                    right: null,
                                    bottom: null,
                                    width: 42.0,
                                    height: 25.0,
                                    child: GeneratedNb1Widget1(),
                                  ),
                                  Positioned(
                                    left: 230.0,
                                    top: 503.0,
                                    right: null,
                                    bottom: null,
                                    width: 152.09605407714844,
                                    height: 135.5,
                                    child: GeneratedEllipse24Widget1(),
                                  ),
                                  Positioned(
                                    left: 239.0,
                                    top: 597.0,
                                    right: null,
                                    bottom: null,
                                    width: 34.0,
                                    height: 34.0,
                                    child: GeneratedConverse1Widget1(),
                                  ),
                                  Positioned(
                                    left: 132.0,
                                    top: 507.0,
                                    right: null,
                                    bottom: null,
                                    width: 47.0,
                                    height: 34.0,
                                    child: GeneratedAdidas1Widget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 595.0,
                                    right: null,
                                    bottom: null,
                                    width: 44.0,
                                    height: 38.0,
                                    child: GeneratedReebok1Widget1(),
                                  ),
                                  Positioned(
                                    left: 342.0,
                                    top: 642.0,
                                    right: null,
                                    bottom: null,
                                    width: 69.0,
                                    height: 41.0,
                                    child: GeneratedMoreWidget(),
                                  ),
                                  Positioned(
                                    left: 235.0,
                                    top: 507.0,
                                    right: null,
                                    bottom: null,
                                    width: 41.0,
                                    height: 38.0,
                                    child: GeneratedPuma1Widget1(),
                                  ),
                                  Positioned(
                                    left: 238.0,
                                    top: 550.0,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 24.0,
                                    child: GeneratedPumaWidget2(),
                                  ),
                                  Positioned(
                                    left: 333.0,
                                    top: 503.67510986328125,
                                    right: null,
                                    bottom: null,
                                    width: 49.0,
                                    height: 49.0,
                                    child: GeneratedEllipse25Widget1(),
                                  ),
                                  Positioned(
                                    left: 339.0,
                                    top: 510.0,
                                    right: null,
                                    bottom: null,
                                    width: 40.0,
                                    height: 38.0,
                                    child: GeneratedAsics2Widget1(),
                                  ),
                                  Positioned(
                                    left: 342.0,
                                    top: 551.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 21.0,
                                    child: GeneratedAsicsWidget2(),
                                  ),
                                  Positioned(
                                    left: 131.0,
                                    top: 639.0,
                                    right: null,
                                    bottom: null,
                                    width: 62.0,
                                    height: 19.0,
                                    child: GeneratedNewBalWidget(),
                                  ),
                                  Positioned(
                                    left: 345.0,
                                    top: 601.0,
                                    right: null,
                                    bottom: null,
                                    width: 25.0,
                                    height: 25.0,
                                    child: GeneratedEllipse26Widget1(),
                                  ),
                                  Positioned(
                                    left: 34.0,
                                    top: 639.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 27.0,
                                    child: GeneratedReebokWidget1(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 507.0,
                                    right: null,
                                    bottom: null,
                                    width: 45.0,
                                    height: 64.0,
                                    child: GeneratedGroup7200Widget1(),
                                  ),
                                  Positioned(
                                    left: 226.0,
                                    top: 640.0,
                                    right: null,
                                    bottom: null,
                                    width: 83.0,
                                    height: 30.0,
                                    child: GeneratedConverseWidget1(),
                                  ),
                                  Positioned(
                                    left: 135.0,
                                    top: 550.0,
                                    right: null,
                                    bottom: null,
                                    width: 57.0,
                                    height: 24.0,
                                    child: GeneratedAdidasWidget2(),
                                  ),
                                  Positioned(
                                    left: 35.0,
                                    top: 173.0,
                                    right: null,
                                    bottom: null,
                                    width: 283.0,
                                    height: 306.0,
                                    child: GeneratedImage1Widget1(),
                                  ),
                                  Positioned(
                                    left: 351.0,
                                    top: 612.0,
                                    right: null,
                                    bottom: null,
                                    width: 14.0,
                                    height: 2.0,
                                    child: GeneratedGroup7201Widget1(),
                                  ),
                                  Positioned(
                                    left: 22.0,
                                    top: 685.0,
                                    right: null,
                                    bottom: null,
                                    width: 86.0,
                                    height: 28.0,
                                    child: GeneratedPopulerWidget1(),
                                  ),
                                  Positioned(
                                    left: 332.0,
                                    top: 686.0,
                                    right: null,
                                    bottom: null,
                                    width: 67.0,
                                    height: 27.0,
                                    child: GeneratedSemuaWidget1(),
                                  ),
                                  Positioned(
                                    left: 18.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 52.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2603Widget1(),
                                  ),
                                  Positioned(
                                    left: 172.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2604Widget1(),
                                  ),
                                  Positioned(
                                    left: 256.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2606Widget1(),
                                  ),
                                  Positioned(
                                    left: 340.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2607Widget9(),
                                  ),
                                  Positioned(
                                    left: 88.0,
                                    top: 725.0,
                                    right: null,
                                    bottom: null,
                                    width: 66.0,
                                    height: 34.0,
                                    child: GeneratedRectangle2605Widget1(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 27.0,
                                    height: 23.0,
                                    child: GeneratedAllWidget1(),
                                  ),
                                  Positioned(
                                    left: 103.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 41.0,
                                    height: 24.0,
                                    child: GeneratedNikeWidget9(),
                                  ),
                                  Positioned(
                                    left: 184.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 50.0,
                                    height: 23.0,
                                    child: GeneratedPumaWidget3(),
                                  ),
                                  Positioned(
                                    left: 267.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 48.0,
                                    height: 23.0,
                                    child: GeneratedAsicsWidget3(),
                                  ),
                                  Positioned(
                                    left: 349.0,
                                    top: 732.0,
                                    right: null,
                                    bottom: null,
                                    width: 60.0,
                                    height: 26.0,
                                    child: GeneratedAdidasWidget3(),
                                  ),
                                  Positioned(
                                    left: 224.0,
                                    top: 814.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7238Widget(),
                                  ),
                                  Positioned(
                                    left: 224.0,
                                    top: 1081.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7234Widget1(),
                                  ),
                                  Positioned(
                                    left: 38.0,
                                    top: 1081.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7235Widget1(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 1277.0,
                                    right: null,
                                    bottom: null,
                                    width: 158.0,
                                    height: 42.0,
                                    child: GeneratedNikeAirJordanWidget3(),
                                  ),
                                  Positioned(
                                    left: 242.0,
                                    top: 1000.0,
                                    right: null,
                                    bottom: null,
                                    width: 141.0,
                                    height: 66.0,
                                    child: GeneratedReebokZpump25Widget1(),
                                  ),
                                  Positioned(
                                    left: 242.0,
                                    top: 1267.0,
                                    right: null,
                                    bottom: null,
                                    width: 141.0,
                                    height: 66.0,
                                    child: GeneratedNikeAirMaxFlyknitWidget3(),
                                  ),
                                  Positioned(
                                    left: 40.0,
                                    top: 814.0,
                                    right: null,
                                    bottom: null,
                                    width: 170.0,
                                    height: 170.0,
                                    child: GeneratedGroup7232Widget2(),
                                  ),
                                  Positioned(
                                    left: 33.0,
                                    top: 998.0,
                                    right: null,
                                    bottom: null,
                                    width: 179.0,
                                    height: 49.0,
                                    child: GeneratedNikeHyperAdaptWidget5(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: -30.0,
              width: 428.0,
              height: 93.0,
              child: GeneratedGroup7237Widget1(),
            )
          ]),
    ));
  }
}
