import 'package:flutter/material.dart';

/* UndefinedNode Alfa web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlfawebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
