import 'package:flutter/material.dart';

/* UndefinedNode Alamat Web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAlamatWebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
