import 'package:flutter/material.dart';

/* UndefinedNode Login 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin3Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
