import 'package:flutter/material.dart';

/* UndefinedNode Gopay web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGopaywebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
