import 'package:flutter/material.dart';

/* UndefinedNode Login 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogin2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(),
    ));
  }
}
