import 'package:flutter/material.dart';

/* UndefinedNode Qris Web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQrisWebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
