import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget/generated/GeneratedBarangmuakansegarakamikirimWidget.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget/generated/GeneratedEllipse41Widget.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget/generated/GeneratedSelamatpembayaranandasudahberhasilWidget.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget/generated/GeneratedGroup7144Widget1.dart';
import 'package:flutterapp/shoessportapp/generateddonewidget/generated/GeneratedCeklis1Widget.dart';

/* Frame Done
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 87.0,
                              right: null,
                              bottom: null,
                              width: 396.0,
                              height: 68.0,
                              child:
                                  GeneratedSelamatpembayaranandasudahberhasilWidget(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 817.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 52.0,
                              child: GeneratedGroup7144Widget1(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 661.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 78.0,
                              child:
                                  GeneratedBarangmuakansegarakamikirimWidget(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 251.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 311.0,
                              child: GeneratedEllipse41Widget(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 302.0,
                              right: null,
                              bottom: null,
                              width: 186.0,
                              height: 192.0,
                              child: GeneratedCeklis1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
