import 'package:flutter/material.dart';

/* UndefinedNode Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
