import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7240Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7238Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedKategoriWidget7.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedRectangle70Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7236Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedNikeWidget11.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7239Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedNIkeConverseNewBalancePumaReebokAsicsAdidasWidget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7246Widget.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7297Widget5.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup7237Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget2/generated/GeneratedGroup19Widget.dart';

/* Frame Home Pages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePagesWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 746.0,
                              height: 375.0,
                              child: GeneratedGroup21Widget(),
                            ),
                            Positioned(
                              left: 920.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 177.0,
                              child: GeneratedGroup20Widget(),
                            ),
                            Positioned(
                              left: 920.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 177.0,
                              child: GeneratedGroup19Widget(),
                            ),
                            Positioned(
                              left: 1059.0,
                              top: 48.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 41.0,
                              child: GeneratedGroup7236Widget1(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 40.0,
                              child: GeneratedKategoriWidget7(),
                            ),
                            Positioned(
                              left: 189.0,
                              top: 877.0,
                              right: null,
                              bottom: null,
                              width: 1092.0,
                              height: 36.0,
                              child:
                                  GeneratedNIkeConverseNewBalancePumaReebokAsicsAdidasWidget(),
                            ),
                            Positioned(
                              left: 851.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedGroup7237Widget3(),
                            ),
                            Positioned(
                              left: 518.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedGroup7238Widget2(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 905.0,
                              height: 70.0,
                              child: GeneratedGroup7239Widget(),
                            ),
                            Positioned(
                              left: 1197.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedGroup7240Widget(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 1208.0,
                              height: 119.8046875,
                              child: GeneratedGroup7246Widget(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 72.0,
                              height: 44.0,
                              child: GeneratedNikeWidget11(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedRectangle70Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7297Widget5(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
