import 'package:flutter/material.dart';

/* UndefinedNode Daftar 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftar2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
