import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7104Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7134Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7105Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7133Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7136Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeZoomKD10OreoWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7107Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeAirMax270sWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeAirMaxWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7103Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7106Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeZoomXWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeReactPrestoLowWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7231Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7114Widget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeHyperAdaptTwoWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeJuvenateKnitWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeAirMaxFlyknitWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeHyperAdaptWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedNikeAirJordanWidget.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget/generated/GeneratedGroup7135Widget.dart';

/* Frame Nike
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNikeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1436.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1436.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 233.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7107Widget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 667.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7103Widget(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 1172.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7133Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 1172.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7134Widget(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7135Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 169.0,
                              child: GeneratedGroup7136Widget(),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7104Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7105Widget(),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7106Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7114Widget(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 62.0,
                              child: GeneratedNikeAirMaxWidget(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 49.0,
                              child: GeneratedNikeHyperAdaptWidget(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 150.0,
                              height: 62.0,
                              child: GeneratedNikeJuvenateKnitWidget(),
                            ),
                            Positioned(
                              left: 250.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 32.0,
                              child: GeneratedNikeZoomXWidget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 846.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 62.0,
                              child: GeneratedNikeHyperAdaptTwoWidget(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 847.0,
                              right: null,
                              bottom: null,
                              width: 131.0,
                              height: 59.0,
                              child: GeneratedNikeZoomKD10OreoWidget(),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 1090.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 61.0,
                              child: GeneratedNikeReactPrestoLowWidget(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 1090.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 64.0,
                              child: GeneratedNikeAirMax270sWidget(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 1368.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 42.0,
                              child: GeneratedNikeAirJordanWidget(),
                            ),
                            Positioned(
                              left: 248.0,
                              top: 1358.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 66.0,
                              child: GeneratedNikeAirMaxFlyknitWidget(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 67.0,
                              right: null,
                              bottom: null,
                              width: 127.0,
                              height: 48.0,
                              child: GeneratedGroup7231Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
