import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget2/generated/GeneratedGroup7160Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget2/generated/GeneratedGroup7159Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget2/generated/GeneratedSpt1Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget2/generated/GeneratedMasuksebagaiGuestWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget2/generated/GeneratedSportsShoesWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget2/generated/GeneratedTrustedQualityGuaranteedWidget.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 30.0,
                              top: 699.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 60.0,
                              child: GeneratedGroup7159Widget(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 783.0,
                              right: null,
                              bottom: null,
                              width: 369.0,
                              height: 60.0,
                              child: GeneratedGroup7160Widget(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 470.0,
                              right: null,
                              bottom: null,
                              width: 308.0,
                              height: 187.0,
                              child: GeneratedTrustedQualityGuaranteedWidget(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 293.0,
                              height: 330.0,
                              child: GeneratedSpt1Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 91.0,
                              bottom: null,
                              width: 244.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: -367.00,
                                  z: 0,
                                  child: GeneratedSportsShoesWidget()),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 855.0,
                              right: null,
                              bottom: null,
                              width: 242.0,
                              height: 35.0,
                              child: GeneratedMasuksebagaiGuestWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
