import 'package:flutter/material.dart';

/* UndefinedNode Size 43
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSize43Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
