import 'package:flutter/material.dart';

/* UndefinedNode Centang 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCentang2Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
