import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedEllipse37Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedGroup7122Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedKeranjangkamuWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedGroup7143Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedKeranjangWidget5.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedGroup7132Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedNikeHyperAdaptSize43Rp998000Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedNikeZoomKD10OreoSize42Rp789999Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedkeranjang2widget/generated/GeneratedGroup7117Widget3.dart';

/* Frame Keranjang2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKeranjang2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 206.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 117.0,
                              child: GeneratedGroup7122Widget1(),
                            ),
                            Positioned(
                              left: 28.0,
                              top: 351.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 117.0,
                              child: GeneratedGroup7132Widget3(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 69.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7117Widget3(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 74.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 48.0,
                              child: GeneratedKeranjangWidget5(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 161.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 34.0,
                              child: GeneratedKeranjangkamuWidget2(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 221.0,
                              right: null,
                              bottom: null,
                              width: 176.0,
                              height: 84.0,
                              child:
                                  GeneratedNikeHyperAdaptSize43Rp998000Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 823.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 52.0,
                              child: GeneratedGroup7143Widget2(),
                            ),
                            Positioned(
                              left: 165.0,
                              top: 374.0,
                              right: null,
                              bottom: null,
                              width: 221.0,
                              height: 75.0,
                              child:
                                  GeneratedNikeZoomKD10OreoSize42Rp789999Widget2(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 278.0,
                              right: null,
                              bottom: null,
                              width: 33.0,
                              height: 33.0,
                              child: GeneratedEllipse37Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
