import 'package:flutter/material.dart';

/* UndefinedNode Centang web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCentangwebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
