import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget2/generated/GeneratedGroup7189Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget2/generated/GeneratedGroup7188Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget2/generated/GeneratedGroup7162Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget2/generated/GeneratedLine130Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedpesanansayawidget2/generated/GeneratedPesananSayaWidget3.dart';

/* Frame Pesanan Saya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPesananSayaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 43.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 26.0,
                              child: GeneratedPesananSayaWidget3(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 99.0,
                              right: null,
                              bottom: null,
                              width: 397.0,
                              height: 1.0,
                              child: GeneratedLine130Widget1(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 371.0,
                              height: 146.0,
                              child: GeneratedGroup7189Widget2(),
                            ),
                            Positioned(
                              left: 29.0,
                              top: 31.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7188Widget3(),
                            ),
                            Positioned(
                              left: -1421.0,
                              top: 835.0,
                              right: null,
                              bottom: null,
                              width: 1828.0,
                              height: 55.0,
                              child: GeneratedGroup7162Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
