import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7298Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup21Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7236Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup20Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedNIkeConverseNewBalancePumaReebokAsicsAdidasWidget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7246Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedKategoriWidget10.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7238Widget4.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup19Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7239Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7240Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedNikeWidget15.dart';
import 'package:flutterapp/shoessportapp/generatedhomepageswidget4/generated/GeneratedGroup7237Widget5.dart';

/* Frame Home Pages
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePagesWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 119.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 746.0,
                              height: 375.0,
                              child: GeneratedGroup21Widget2(),
                            ),
                            Positioned(
                              left: 920.0,
                              top: 325.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 177.0,
                              child: GeneratedGroup20Widget2(),
                            ),
                            Positioned(
                              left: 920.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 414.0,
                              height: 177.0,
                              child: GeneratedGroup19Widget2(),
                            ),
                            Positioned(
                              left: 1059.0,
                              top: 48.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 41.0,
                              child: GeneratedGroup7236Widget3(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 740.0,
                              right: null,
                              bottom: null,
                              width: 114.0,
                              height: 40.0,
                              child: GeneratedKategoriWidget10(),
                            ),
                            Positioned(
                              left: 189.0,
                              top: 877.0,
                              right: null,
                              bottom: null,
                              width: 1092.0,
                              height: 36.0,
                              child:
                                  GeneratedNIkeConverseNewBalancePumaReebokAsicsAdidasWidget2(),
                            ),
                            Positioned(
                              left: 851.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedGroup7237Widget5(),
                            ),
                            Positioned(
                              left: 518.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedGroup7238Widget4(),
                            ),
                            Positioned(
                              left: 183.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 905.0,
                              height: 70.0,
                              child: GeneratedGroup7239Widget2(),
                            ),
                            Positioned(
                              left: 1197.0,
                              top: 796.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 70.0,
                              child: GeneratedGroup7240Widget2(),
                            ),
                            Positioned(
                              left: 162.0,
                              top: 160.0,
                              right: null,
                              bottom: null,
                              width: 1196.2032470703125,
                              height: 95.0,
                              child: GeneratedGroup7246Widget2(),
                            ),
                            Positioned(
                              left: 95.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 72.0,
                              height: 44.0,
                              child: GeneratedNikeWidget15(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7298Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
