import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7135Widget3.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7136Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7133Widget4.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7107Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7103Widget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeWidget7.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7132Widget6.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeHyperAdaptWidget3.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeZoomXWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7106Widget2.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7105Widget2.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeAirMaxFlyknitWidget2.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeReactPrestoLowWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7134Widget3.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeAirMaxWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeAirJordanWidget2.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeHyperAdaptTwoWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeAirMax270sWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7104Widget2.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeZoomKD10OreoWidget3.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedNikeJuvenateKnitWidget1.dart';
import 'package:flutterapp/shoessportapp/generatednikewidget6/generated/GeneratedGroup7114Widget2.dart';

/* Frame Nike
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNikeWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(40.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1436.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 1436.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(40.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(40.0),
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 233.0,
                              top: 669.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7107Widget1(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 667.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7103Widget1(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 1172.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7133Widget4(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 1172.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7134Widget3(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7135Widget3(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 912.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 169.0,
                              child: GeneratedGroup7136Widget1(),
                            ),
                            Positioned(
                              left: 235.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7104Widget2(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7105Widget2(),
                            ),
                            Positioned(
                              left: 237.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7106Widget2(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 149.0,
                              right: null,
                              bottom: null,
                              width: 170.0,
                              height: 170.0,
                              child: GeneratedGroup7114Widget2(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 76.0,
                              right: null,
                              bottom: null,
                              width: 72.0,
                              height: 44.0,
                              child: GeneratedNikeWidget7(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 142.0,
                              height: 62.0,
                              child: GeneratedNikeAirMaxWidget1(),
                            ),
                            Positioned(
                              left: 230.0,
                              top: 333.0,
                              right: null,
                              bottom: null,
                              width: 179.0,
                              height: 49.0,
                              child: GeneratedNikeHyperAdaptWidget3(),
                            ),
                            Positioned(
                              left: 57.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 190.0,
                              height: 50.0,
                              child: GeneratedNikeJuvenateKnitWidget1(),
                            ),
                            Positioned(
                              left: 250.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 32.0,
                              child: GeneratedNikeZoomXWidget1(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 852.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 35.0,
                              child: GeneratedNikeHyperAdaptTwoWidget1(),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 847.0,
                              right: null,
                              bottom: null,
                              width: 131.0,
                              height: 59.0,
                              child: GeneratedNikeZoomKD10OreoWidget3(),
                            ),
                            Positioned(
                              left: 40.0,
                              top: 67.0,
                              right: null,
                              bottom: null,
                              width: 48.0,
                              height: 48.0,
                              child: GeneratedGroup7132Widget6(),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 1090.0,
                              right: null,
                              bottom: null,
                              width: 119.0,
                              height: 61.0,
                              child: GeneratedNikeReactPrestoLowWidget1(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 1090.0,
                              right: null,
                              bottom: null,
                              width: 99.0,
                              height: 64.0,
                              child: GeneratedNikeAirMax270sWidget1(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 1368.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 42.0,
                              child: GeneratedNikeAirJordanWidget2(),
                            ),
                            Positioned(
                              left: 248.0,
                              top: 1358.0,
                              right: null,
                              bottom: null,
                              width: 141.0,
                              height: 66.0,
                              child: GeneratedNikeAirMaxFlyknitWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
