import 'package:flutter/material.dart';

/* UndefinedNode Code 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCode2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
