import 'package:flutter/material.dart';

/* UndefinedNode Dana
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDanaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
