import 'package:flutter/material.dart';

/* UndefinedNode Qris
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQrisWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
