import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7140Widget6.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7145Widget5.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedLine42Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7144Widget5.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7151Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7143Widget8.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7148Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7150Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7149Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7146Widget3.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7141Widget6.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7147Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7299Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7142Widget4.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7247Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7248Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedprodukwidget1/generated/GeneratedGroup7214Widget4.dart';

/* Frame Produk
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProdukWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1537.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1537.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 305.0,
                              top: 1288.0,
                              right: null,
                              bottom: null,
                              width: 1003.0,
                              height: 1.0,
                              child: GeneratedLine42Widget1(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 105.07293701171875,
                              child: GeneratedFrame2Widget(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7140Widget6(),
                            ),
                            Positioned(
                              left: 382.0,
                              top: 647.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7144Widget5(),
                            ),
                            Positioned(
                              left: 378.0,
                              top: 1013.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7148Widget1(),
                            ),
                            Positioned(
                              left: 1132.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7143Widget8(),
                            ),
                            Positioned(
                              left: 1132.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7145Widget5(),
                            ),
                            Positioned(
                              left: 1128.0,
                              top: 1009.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7149Widget3(),
                            ),
                            Positioned(
                              left: 882.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7141Widget6(),
                            ),
                            Positioned(
                              left: 882.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7146Widget3(),
                            ),
                            Positioned(
                              left: 878.0,
                              top: 1009.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7150Widget3(),
                            ),
                            Positioned(
                              left: 632.0,
                              top: 285.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7142Widget4(),
                            ),
                            Positioned(
                              left: 632.0,
                              top: 643.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7147Widget2(),
                            ),
                            Positioned(
                              left: 628.0,
                              top: 1009.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 230.0,
                              child: GeneratedGroup7151Widget3(),
                            ),
                            Positioned(
                              left: 1069.0,
                              top: 29.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 42.16803741455078,
                              child: GeneratedGroup7214Widget4(),
                            ),
                            Positioned(
                              left: 147.0,
                              top: 125.0,
                              right: null,
                              bottom: null,
                              width: 1195.0,
                              height: 95.0,
                              child: GeneratedGroup7247Widget2(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: null,
                              right: null,
                              bottom: 466.0,
                              width: 217.0,
                              height: 571.0,
                              child: GeneratedGroup7248Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1402.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7299Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
