import 'package:flutter/material.dart';

/* UndefinedNode Link aja web
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLinkajawebWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
