import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedloginanddaftarwidget/generated/GeneratedKeluarWidget.dart';
import 'package:flutterapp/shoessportapp/generatedloginanddaftarwidget/generated/GeneratedLine122Widget.dart';
import 'package:flutterapp/shoessportapp/generatedloginanddaftarwidget/generated/GeneratedGroup7301Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedloginanddaftarwidget/generated/GeneratedGroup7227Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedloginanddaftarwidget/generated/GeneratedSilahkanDaftaratauLoginterlebihdahulusupayabisamenikmat1.dart';

/* Frame Login andDaftar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginandDaftarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 431.0,
                              top: 130.0,
                              right: null,
                              bottom: null,
                              width: 579.0,
                              height: 161.0,
                              child:
                                  GeneratedSilahkanDaftaratauLoginterlebihdahulusupayabisamenikmat1(),
                            ),
                            Positioned(
                              left: 672.0,
                              top: 759.0,
                              right: null,
                              bottom: null,
                              width: 118.0,
                              height: 58.0,
                              child: GeneratedKeluarWidget(),
                            ),
                            Positioned(
                              left: 431.0,
                              top: 488.0,
                              right: null,
                              bottom: null,
                              width: 595.0,
                              height: 215.0,
                              child: GeneratedGroup7227Widget1(),
                            ),
                            Positioned(
                              left: 72.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 1313.006103515625,
                              height: 1.0,
                              child: GeneratedLine122Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7301Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
