import 'package:flutter/material.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7255Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7265Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7290Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedEditWidget6.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7256Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7288Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedLine109Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedMhmdzakigmailcomWidget1.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/Generated085646651029Widget11.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7305Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedPilihGambarWidget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedProfilSayaKelolainformasiprofilAndauntukmengontrolmelin.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7250Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7207Widget4.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedLine103Widget.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7250Widget1.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7187Widget2.dart';
import 'package:flutterapp/shoessportapp/generatedprofilwidget9/generated/GeneratedGroup7186Widget2.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1160.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1160.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(204, 17, 17, 17),
                              ),
                            ),
                            Positioned(
                              left: 388.0,
                              top: 417.0,
                              right: null,
                              bottom: null,
                              width: 991.00048828125,
                              height: 1.0,
                              child: GeneratedLine103Widget(),
                            ),
                            Positioned(
                              left: 388.0,
                              top: 329.0,
                              right: null,
                              bottom: null,
                              width: 821.0,
                              height: 82.0,
                              child:
                                  GeneratedProfilSayaKelolainformasiprofilAndauntukmengontrolmelin(),
                            ),
                            Positioned(
                              left: 423.0,
                              top: 453.992919921875,
                              right: null,
                              bottom: null,
                              width: 168.385986328125,
                              height: 356.008056640625,
                              child: GeneratedGroup7186Widget2(),
                            ),
                            Positioned(
                              left: 1058.0,
                              top: 810.0,
                              right: null,
                              bottom: null,
                              width: 358.0055847167969,
                              height: 1.0,
                              child: GeneratedLine109Widget(),
                            ),
                            Positioned(
                              left: 1184.0,
                              top: 666.0,
                              right: null,
                              bottom: null,
                              width: 129.0,
                              height: 34.0,
                              child: GeneratedPilihGambarWidget(),
                            ),
                            Positioned(
                              left: 684.0,
                              top: 474.0,
                              right: null,
                              bottom: null,
                              width: 670.0,
                              height: 502.0,
                              child: GeneratedGroup7187Widget2(),
                            ),
                            Positioned(
                              left: 38.0,
                              top: 299.0,
                              right: null,
                              bottom: null,
                              width: 282.5,
                              height: 618.029541015625,
                              child: GeneratedGroup7207Widget4(),
                            ),
                            Positioned(
                              left: 152.0,
                              top: 118.0,
                              right: null,
                              bottom: null,
                              width: 1208.0,
                              height: 114.2265625,
                              child: GeneratedGroup7250Widget1(),
                            ),
                            Positioned(
                              left: 1067.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 346.0,
                              height: 42.6953125,
                              child: GeneratedGroup7250Widget2(),
                            ),
                            Positioned(
                              left: 684.0,
                              top: 642.0,
                              right: null,
                              bottom: null,
                              width: 217.0,
                              height: 29.0,
                              child: GeneratedMhmdzakigmailcomWidget1(),
                            ),
                            Positioned(
                              left: 684.0,
                              top: 726.0,
                              right: null,
                              bottom: null,
                              width: 151.0,
                              height: 29.0,
                              child: Generated085646651029Widget11(),
                            ),
                            Positioned(
                              left: 418.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 902.0,
                              height: 54.0,
                              child: GeneratedGroup7265Widget(),
                            ),
                            Positioned(
                              left: 988.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 32.0,
                              child: GeneratedEditWidget6(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 476.0,
                              right: null,
                              bottom: null,
                              width: 1255.0,
                              height: 208.90940856933594,
                              child: GeneratedGroup7255Widget(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 636.0,
                              right: null,
                              bottom: null,
                              width: 218.0,
                              height: 47.0,
                              child: GeneratedGroup7256Widget(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 558.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 50.0,
                              child: GeneratedGroup7290Widget(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 711.0,
                              right: null,
                              bottom: null,
                              width: 177.0,
                              height: 47.0,
                              child: GeneratedGroup7288Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 1025.0,
                              right: null,
                              bottom: null,
                              width: 1440.0,
                              height: 135.0,
                              child: GeneratedGroup7305Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
