import 'package:flutter/material.dart';

/* Text Mewakili
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMewakiliWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Mewakili''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272435238486,
        fontSize: 95.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
